language: node_js
node_js:
 - "8"
 - "10"
 - "node"
services:
 - postgresql
install:
 - npm install
before_script:
  - psql -c "CREATE USER ppt WITH PASSWORD 'ppt42';" -U postgres
  - psql -c "CREATE DATABASE ppt OWNER ppt;" -U postgres
script:
 - npm test