language: node_js
node_js:
 - "8"
 - "10"
 - "node"
addons:
 mariadb: "10.1"
 apt:
  packages:
   - mariadb-client
install:
 - npm install
before_script:
 - sudo mariadb < tests/SetupMariaDB.sql
script:
 - npm test