- hosts: all
  remote_user: pi
  become_method: sudo
  name: "Backup Presentaciones"
  tasks:
    - name: Backup Presentaciones SQL
      become: yes
      shell: docker-compose exec postgres pg_dump -U postgres postgres > backup.sql
      args:
        chdir: /home/pi/presentaciones

    - name: Download SQL backup
      fetch:
        src: /home/pi/presentaciones/backup.sql
        dest: backups/ppt.sql
        flat: yes

    - name: Backup static
      command: tar cvf backup-ppt.tar presentaciones/static
      args:
        chdir: /home/pi

    - name: Download static backup
      fetch:
        src: /home/pi/backup-ppt.tar
        dest: backups/ppt.tar
        flat: yes

    - name: Compress Presentaciones Backup
      local_action: archive
      args:
        path: 
        - backups/ppt.tar
        - backups/ppt.sql
        dest: backups/ppt-{{ ansible_date_time.date }}.tar.xz
        format: xz