name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Presentaciones
      run: cp config.json.sample config.json
    - name: Build Docker images
      run: docker-compose build
    - name: Execute tests
      run: docker-compose run app npm test
